plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group 'com.hyejin'
version '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

test {
    useJUnitPlatform()
}

// bootJar 비활성화
tasks.withType(org.springframework.boot.gradle.tasks.bundling.BootJar).configureEach {
    enabled = false
}

task copyStaticResources(type: Copy) {
    // 1. 소스 위치: util 모듈의 실제 정적 파일 위치
    from 'src/main/resources'

    // 2. 목적지 위치: app 모듈의 빌드/리소스 폴더
    // app 모듈의 빌드 폴더에 복사
    destinationDir project(':app').file('src/main/resources')

    // 복사 시점 로그 출력
    doLast {
        println "Copied static resources from util to app/src/main/resources/static"
    }
}