server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    import: classpath:variables.yml
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb+srv://hyejin:qkrgpwls929!@counselorcluster.hqskivq.mongodb.net/counselor?retryWrites=true&w=majority&appName=counselorCluster
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: chat-proccesser
      auto-offset-reset: latest
      properties:
        spring.json.value.default.type: com.hyejin.counselor.core.entity.Chat
        spring.json.use.type.headers: false

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.orm.jdbc.bind: trace
